version: '3'
services:
  web:
    container_name: 'hal-article-web'
    image: "540688370389.dkr.ecr.eu-west-1.amazonaws.com/low-emedia/hal-nginx:latest"
    environment:
      SITE_NAME: 'hal-article-v2.local'
      PROTOCOL: 'http'
      SERVER_LANG: 'php'
    ports:
      - "8082:80"
    volumes:
      - ./appcode:/var/www/html/

    links:
      - php:php-fpm
      
  php:
    container_name: 'hal-article-php'
    build:
     context: .
     dockerfile: Dockerfile
    environment:
      APP_ENV: 'development'
      COMPOSER_INSTALL: 'true'

      DB_ARTICLE_HOST: ''
      DB_ARTICLE_SCHEMA: ''
      DB_ARTICLE_USER: ''
      DB_ARTICLE_PASSWORD: ''

      ELASTICSEARCH_ARTICLE_HOST: ''

      MICROSERVICE_CATEGORY_URL: 'hal-category-web'

    volumes:
      - ./appcode:/var/www/html/

networks:
    default:
        external:
            name: halv2_default
