version: '3'
services:
  web:
    container_name: 'hal-article-web'
    build:
      context: .
      dockerfile: nginx/Dockerfile
#    image: "nginx:latest"
#    image: "540688370389.dkr.ecr.eu-west-1.amazonaws.com/low-emedia/hal-nginx:latest"
#    environment:
#      SITE_NAME: 'hal-article-v2.discovery'
#      PROTOCOL: 'http'
#      SERVER_LANG: 'php'
    ports:
      - "8082:80"
    volumes:
      - ./appcode:/var/www/html

    links:
      - php:php-fpm
    depends_on:
      - php

  mysql:
    container_name: 'hal-article-mysql'
    build:
      context: .
      dockerfile: mysql/Dockerfile
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3325:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'hal-articles'

  php:
    container_name: 'hal-article-php'
    build:
     context: .
     dockerfile: Dockerfile
    environment:
      APP_ENV: 'development'
      COMPOSER_INSTALL: 'true'
      DB_ARTICLE_HOST: 'hal-article-mysql'
      DB_ARTICLE_SCHEMA: 'hal-articles'
      DB_ARTICLE_USER: 'root'
      DB_ARTICLE_PASSWORD: 'admin'
      ELASTICSEARCH_ARTICLE_HOST: 'hal-article-elasticsearch:9200'
      MICROSERVICE_CATEGORY_URL: 'hal-category-web'

      AWS_ACCESS_KEY: "AKIAJ76WTB7QKINSCVYA"
      AWS_SECRET_KEY: "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"

      AWS_SQS_QUEUE: "http://hal-message-broker-sqs:9324/queue/default"

#      XDEBUG_CONFIG: remote_host=host.docker.internal

    volumes:
      - ./appcode:/var/www/html

    depends_on:
      - mysql
      - elasticsearch

  swagger:
    container_name: hal-article-swagger
    image: swaggerapi/swagger-ui
    volumes:
      - ./appcode:/app:cached

    ports:
      - "8080:8080"

    environment:
      SWAGGER_JSON: '/app/openapi.json'
      BASE_URL: '/'

# docker run -d -p 80:8080 swaggerapi/swagger-editor

  elasticsearch:
    container_name: 'hal-article-elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.5.3'
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.conf:/etc/elasticsearch/elasticsearch.yml
    depends_on:
      - mysql
    environment:
      - 'cluster.name=docker-cluster'
      - 'bootstrap.memory_lock=true'
#      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1

  message-queue:
    container_name: hal-article-sqs
    image: roribio16/alpine-sqs
    ports:
      - "9330:9324"
#      - "9331:9325"

#  elasticsearch2:
#    container_name: 'hal-article-elasticsearch-2'
#    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.5.3'
#    ports:
#      - "9202:9200"
#      - "9302:9300"
#    volumes:
#      #      - ./elasticsearch/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/config/elasticsearch.conf:/etc/elasticsearch/elasticsearch.yml
#    depends_on:
#      - elasticsearch
#      - mysql
#    environment:
#      - 'cluster.name=docker-cluster'
#      - 'bootstrap.memory_lock=true'
#      - 'xpack.security.enabled=false'
#      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
#      - "discovery.zen.ping.unicast.hosts=hal-article-elasticsearch"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#
#  elasticsearch3:
#    container_name: 'hal-article-elasticsearch-3'
#    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.5.3'
#    ports:
#      - "9203:9200"
#      - "9303:9300"
#    volumes:
#      #      - ./elasticsearch/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/config/elasticsearch.conf:/etc/elasticsearch/elasticsearch.yml
#    depends_on:
#      - elasticsearch
#      - elasticsearch2
#      - mysql
#    environment:
#      - 'cluster.name=docker-cluster'
#      - 'bootstrap.memory_lock=true'
#      - 'xpack.security.enabled=false'
#      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
#      - "discovery.zen.ping.unicast.hosts=hal-article-elasticsearch"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

networks:
    default:
        external:
            name: halv2_default
